/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class guyuanjun_com_ndk01_JniTest */

#ifndef _Included_guyuanjun_com_ndk01_JniTest
#define _Included_guyuanjun_com_ndk01_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     guyuanjun_com_ndk01_JniTest
 * Method:    get
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_guyuanjun_com_ndk01_JniTest_get
  (JNIEnv *, jobject);

/*
 * Class:     guyuanjun_com_ndk01_JniTest
 * Method:    set
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_guyuanjun_com_ndk01_JniTest_set
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
